services: 

  db:
    image: mysql:8.0
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: todo_go_db
    ports: 
      - "3310:3306"
    healthcheck: 
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  app: 
    build: 
      context: .
    ports:
      - "8088:8088"
    depends_on:
      db: 
        condition: service_healthy
    env_file: 
      - .env





